name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 1 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: # Or as an environment variable
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD https://ghcr.io
        docker build --file Dockerfile --tag ghcr.io/andrewmichaelsmith/tor-relay/tor-relay:latest .
        TOR_VERSION=$(docker run --entrypoint tor ghcr.io/andrewmichaelsmith/tor-relay/tor-relay:latest --version | sed -n 2p | cut -d' ' -f 3)
        IMAGE_VERSION=$TOR_VERSION$GITHUB_RUN_NUMBER
        echo $IMAGE_VERSION
        docker tag ghcr.io/andrewmichaelsmith/tor-relay/tor-relay:latest ghcr.io/andrewmichaelsmith/tor-relay/tor-relay:$IMAGE_VERSION
        docker push ghcr.io/andrewmichaelsmith/tor-relay/tor-relay:latest
        docker push ghcr.io/andrewmichaelsmith/tor-relay/tor-relay:$IMAGE_VERSION

