name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 1 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: # Or as an environment variable
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.pkg.github.com
        docker build --file Dockerfile --tag docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:latest .
        TOR_VERSION=$(docker run --entrypoint tor docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:latest --version | sed -n 2p | cut -d'' '' -f 3)
        IMAGE_VERSION=$TOR_VERSION$GITHUB_RUN_NUMBER
        echo $IMAGE_VERSION
        docker tag docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:latest docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:$IMAGE_VERSION
        docker push docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:latest
        docker push docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:$IMAGE_VERSION

