name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.pkg.github.com
        docker build . --file Dockerfile --tag docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:latest .
        docker push docker.pkg.github.com/andrewmichaelsmith/tor-relay/tor-relay:latest
